#APP ENV
app:
  env: "dev" # dev,release
  sysname: "ZAManager"
  port: 80
  domain: http://192.168.2.80:9534

#Mysql
mysql:
  dbname: "zta"
  prefix: "zta_"
  pool:
    pool-min-cap: 10
    pool-ex-cap: 5
    pool-max-cap: 40
    pool-idle-timeout: 3600
    pool-wait-count: 1000
    pool-wai-timeout: 30
  write:
    host: "192.168.2.80"
    port: 3306
    user: "root"
    password: "123456"

#Redis
redis:
  addr: "192.168.2.80:6379"

#CA
ca:
  base-url: "http://192.168.2.80:8382"
  sign-url: "https://192.168.2.80:8681"
  ocsp-url: "http://192.168.2.80:8383"
  version: "/api/v1"
  auth-key: "0739a645a7d6601d9d45f6b237c4edeadad904f2fce53625dfdd541ec4fc8134"
