#APP ENV
app:
  env: "release" # dev,release
  sysname: "ZAManager"
  port: 8080
  domain: domain.com

#Mysql
mysql:
  dbname: "zta"
  prefix: "zta_"
  pool:
    pool-min-cap: 10
    pool-ex-cap: 5
    pool-max-cap: 40
    pool-idle-timeout: 3600
    pool-wait-count: 1000
    pool-wai-timeout: 30
  write:
    host: "ZTA_MYSQL_HOST"
    port: 3306
    user: "ZTA_MYSQL_USER"
    password: "ZTA_MYSQL_PASSWORD"

#Redis
redis:
  addr: "ZTA_REDIS_ADDR"

#CA
ca:
  base-url: "ZTA_CA_BASE_URL"
  sign-url: "ZTA_CA_SIGN_URL"
  ocsp-url: "ZTA_CA_OCSP_URL"
  version: "/api/v1"
  auth-key: "ZTA_CA_AUTH_KEY"
