version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - zta
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    networks:
      - zta
    volumes:
      - redis-data:/data

  root-ca-tls:
    image: zhangshuainbb/zaca:0.0.2
    command: ["./zaca", "tls"]
    volumes:
      - "./root_ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_HTTP_CA_LISTEN: '0.0.0.0:8083'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_INFLUXDB_ENABLED: 'false'
      IS_KEYMANAGER_SELF_SIGN: 'true'
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/root_cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
    networks:
      - zta
    restart: always

  zaca-tls:
    image: zhangshuainbb/zaca:0.0.2
    command: ["./zaca", "tls"]
    ports:
      - "8081:8081"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
      IS_OCSP_HOST: 'http://zaca-ocsp:8082'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - zta
    restart: always

  zaca-ocsp:
    image: zhangshuainbb/zaca:0.0.2
    command: ["./zaca", "ocsp"]
    ports:
      - "8082:8082"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - zta
    restart: always

  zaca-api:
    image: zhangshuainbb/zaca:0.0.2
    command: ["./zaca", "api"]
    ports:
      - "8080:8080"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - zta
    restart: always

  zta-portal:
    image: rovast/za-portal
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - zta
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  zta-backend:
    image: taosheng205054/zamanager:latest
    restart: always
    environment:
      DOMAIN: ''
      ZTA_REDIS_ADDR: 'redis:6379'
      ZTA_MYSQL_HOST: 'mysql'
      ZTA_MYSQL_USER: 'root'
      ZTA_MYSQL_PASSWORD: 'root'
      ZTA_CA_SIGN_URL: 'https://root-ca-tls:8083'
      ZTA_CA_AUTH_KEY: '0739a645a7d6601d9d45f6b237c4edeadad904f2fce53625dfdd541ec4fc8134'
    depends_on:
      - mysql
      - redis
    networks:
      - zta

networks:
  zta:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
